export const typography = {
  fontFamily: '"Wanted Sans", "Noto Sans KR", sans-serif',
  h1: {
    fontFamily: '"Elice DX Neolli OTF", "Wanted Sans", sans-serif',
    fontSize: '32px',
    fontWeight: 700,
    letterSpacing: '-0.64px',
    lineHeight: 1.2,
  },
  h2: {
    fontFamily: '"Elice DX Neolli OTF", "Wanted Sans", sans-serif',
    fontSize: '24px',
    fontWeight: 700,
    letterSpacing: '-0.48px',
    lineHeight: 1.3,
  },
  h3: {
    fontFamily: '"Elice DX Neolli OTF", "Wanted Sans", sans-serif',
    fontSize: '20px',
    fontWeight: 700,
    letterSpacing: '-0.4px',
    lineHeight: 1.4,
  },
  h4: {
    fontSize: '18px',
    fontWeight: 600,
    letterSpacing: '-0.36px',
    lineHeight: 1.5,
  },
  h5: {
    fontSize: '16px',
    fontWeight: 600,
    letterSpacing: '-0.48px',
    lineHeight: 1.5,
  },
  h6: {
    fontSize: '14px',
    fontWeight: 600,
    letterSpacing: '-0.42px',
    lineHeight: 1.5,
  },
  subtitle1: {
    fontSize: '16px',
    fontWeight: 500,
    letterSpacing: '-0.48px',
    lineHeight: 1.5,
  },
  subtitle2: {
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '-0.42px',
    lineHeight: 1.5,
  },
  body1: {
    fontSize: '16px',
    fontWeight: 400,
    letterSpacing: '-0.48px',
    lineHeight: 1.5,
  },
  body2: {
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: '-0.42px',
    lineHeight: 1.5,
  },
  button: {
    fontSize: '16px',
    fontWeight: 600,
    letterSpacing: '-0.48px',
    textTransform: 'none' as const,
  },
  caption: {
    fontSize: '12px',
    fontWeight: 400,
    letterSpacing: '-0.24px',
    lineHeight: 1.5,
  },
  overline: {
    fontSize: '12px',
    fontWeight: 600,
    letterSpacing: '-0.24px',
    textTransform: 'uppercase' as const,
  },
};